### ISSUE TITLE
Sign Teachers do not drop the book on death

### ISSUE THREAD

**Issue by Lordician** [elucent/eidolon#1]
I have tried with all of them, none of them drop the Ars Ecclesia on death if they were still in the process of writing in it.
While this does make for a good reason to keep the writers safe, it can also lead to some frustration.

Versions
Forge: 1.16.4-forge-35.1.13
Eidolon: eidolon-0.2

Logs:
None of them seemed to have anything out of the ordinary, but i can attach them if you really want.

**Comment by elucent** [comment]
No logs necessary, I'll try to think of a fix to this one. It's a bit tricky with the way the AI works, but with enough hacks anything is possible. :)

**Comment by elucent** [comment]
I think I've fixed this, although I think there may be a slim chance that the codex is lost due to an unknown sync issue. I haven't observed that happening yet though. Will reopen if the bug shows up again, but I'll close this for now in the next commit.

**Comment by elucent** [comment]
Should be fixed in 89b517b4c3754bd70f707c480cf332ac10e100b5.
