### ISSUE TITLE
CurseForge and GitHub licenses mismatch

### ISSUE THREAD

**Issue by Daomephsta** [elucent/eidolon#109]
The only license on the github repo is [Forge's LGPL license](https://github.com/elucent/eidolon/blob/master/LICENSE.txt), but the CurseForge page lists the license as 3-Clause BSD ![](https://user-images.githubusercontent.com/10936237/129855709-b5deb1fe-3a4d-425f-b7c4-bcef906484a4.png)

**Comment by elucent** [comment]
I've removed the forge license from the 1.18 branch, so this will be resolved when I make that branch the new master.
