### ISSUE TITLE
JEI Render is "breaks down"

### ISSUE THREAD

**Issue by AlgorithmLX** [elucent/eidolon#113]
**Describe the bug**
Render is Break down,  for a line greater than 6

**To Reproduce**
Make a Big Craft using datapack or addon

**Environment**
Single and Multiplayer

![Screenshot](https://user-images.githubusercontent.com/46783751/132889137-4c38acf5-d93a-4df1-8971-b1ee169db555.png)

**Comment by elucent** [comment]
The recipe render is intentionally not designed for this, frankly you should not be making recipes like this (or even a tenth as complex) using my system. Closing as wontfix.
