### ISSUE TITLE
Impossible to get Top Hat

### ISSUE THREAD

**Issue by Dragonfire2K** [elucent/eidolon#116]
So when I type @Eidolon in the JEI search bar, I found an interesting looking item, the Top Hat (eidolon:top_hat) but I can't get any guide how to get it. Am I missing something?

**Comment by Alexthw46** [comment]
It's a secret/easter egg item. Just like the music disc you can't get it with standard means so JEI can't show you, but it's not creative only, it's just a secret to everybody how to get it.

**Comment by Dragonfire2K** [comment]
Okay... Any hints where I should look? I mean alone the rituals have at least 5^4 different combinations with all 5 symbols there are currently.
Btw, is it true, that in the current version, 2 of those 5 symbols are without a purpose?

**Comment by elucent** [comment]
Closing since it's not an issue.
