### ISSUE TITLE
Burning pillager banners doesnt give me bad omen

### ISSUE THREAD

**Issue by cobaltlol** [elucent/eidolon#140]
So im playing on a modpack called permafrost eyes of the storm and when i burned the pillager banners, it didnt give me the bad omen effect even though in a video i watched about this modpack, he got bad omen.

**Comment by elucent** [comment]
how does this relate to eidolon?

**Comment by cobaltlol** [comment]
Dont know i just assumed it was related to eidolon cause when you burn it theres the burning animation that looks like when you do the rituals in eidolon
