### ISSUE TITLE
Crucible crashes server when performing any step of a recipe

### ISSUE THREAD

**Issue by asdfagi** [elucent/eidolon#2]
The Crucible is somewhat broken. On my 1.16.4 Minecraft Server, the Crucible crashes every time one of the steps of a recipe is performed (for example throwing in a mushroom for the sprouting fungus recipe). Logging in afterwards reveals that the recipe did progress (in this case, the water turned purple), but I think this is still a pretty big issue.

In case you're wondering, it does work fine on singleplayer, it only crashes the server.

**Comment by elucent** [comment]
Could you please post the crash report?

**Comment by elucent** [comment]
I've managed to reproduce this locally, I think there's a pretty simple cause. Should be fixed in the next commit.

**Comment by elucent** [comment]
Should be fixed in 89b517b4c3754bd70f707c480cf332ac10e100b5.
