### ISSUE TITLE
Ars Ecclesia wording for apothecary brewing stand entry could be improved

### ISSUE THREAD

**Issue by Febilian** [elucent/eidolon#21]
**Describe the bug**
Hey Elu! This is probably a nitpicky kind of suggestion related to the in-game documentation, but I figured if it could confuse me at first glance, it might confuse someone else.

![image](https://user-images.githubusercontent.com/13922447/103281600-14e71300-4988-11eb-9fd6-1ad9114b21fd.png)

The guidebook here refers to the crucible as a _cauldron_ for the block you're supposed to put the apothecary brewing stand on top of.

Since cauldrons exist as a separate block within the base game, some confusion might be avoided if you were to refer to it in-documentation as a boiling _crucible_ for the sake of consistency and clarity.

That's all for now!

**Comment by elucent** [comment]
Oh, whoops. Definitely a minor oversight on my part, I'll fix it for the next version.
