### ISSUE TITLE
Warped Sprouts: Anchoring pronoun usage is either vague or bizarre. 

### ISSUE THREAD

**Issue by Moleculor** [elucent/eidolon#24]
![image](https://user-images.githubusercontent.com/3865976/103367135-eea99c00-4a89-11eb-8c28-7c36dfec4622.png)

When **warped sprouts** are consumed, **they** (the warped sprouts) grant an anchoring effect, causing ***them*** (the warped sprouts? The person eating them?) to become immovable by teleportation (do the warped sprouts teleport? Do I teleport? Wait, can I feed these to endermen, somehow?)...

**Comment by elucent** [comment]
I think this is a typo, probably I was deleting some text to make the entry fit and didn't realize I'd deleted something important. I'll reword it in the next update.

Just to be clear, warped sprouts grant anchoring when eaten, and can be brewed into potions of anchoring that grant longer durations of the effect. Whenever an entity is under the effects of anchoring, teleportation is nullified, so things like ender pearls no longer work. You can use a splash potion of it to prevent endermen from teleporting away from you, or drink it yourself to prevent yourself being unwillingly teleported, such as with Quark's harder endermen or a vanilla pearl stasis chamber. It's not the most useful effect, but it can be handy in certain scenarios.
