### ISSUE TITLE
Brewing ingredients from this mod can't be used on dedicated server

### ISSUE THREAD

**Issue by Ritzumi** [elucent/eidolon#29]
**Describe the bug**
Player can't brew anything using any ingredients given from this mods on multiplayer (singleplayer work fine).
No explicit conflict with other mods found.

**To Reproduce**
Put water bottle on any brewing stand and put in the sprouting fungus as if you are brewing awkward potions, the brew won't progress and the fungus will got either ejected or place in player's inventory.
Later on, tried with other ingredients from this mod, none of them work.

**Environment**
Multiplayer with Eidolon 0.2.4

**Crash Report**
No actual crash report, found this in debug.log, however.
https://gist.github.com/Ritzumi/1d19cf1db9b22ee89d149ea506ee4c12

**Comment by elucent** [comment]
Will be fixed in next commit.
