### ISSUE TITLE
Crystallization Ritual not functioning

### ISSUE THREAD

**Issue by BioOnPC** [elucent/eidolon#3]
Everything seems to be in the right place, but every time I burn bone meal in the brazier, it fizzles out. 

![image](https://user-images.githubusercontent.com/25067089/103041120-77cd4a00-4543-11eb-95e2-d81adf101411.png)

**Comment by elucent** [comment]
Could you post a log and mod list?

**Comment by BioOnPC** [comment]
I am on a server, should I send debug.log or latest.log?

Mod list:
- Alex's Mobs, Ars Nouveau, Artifacts, Astral Sorcery, Bedspreads, Yung's Better Caves, Brazier, Chimes, Chisels and Bits, Shulker's Faithful Factories, Comforts, Console Experience, Cosmetic Armor Reworked, Create, Crumbs, Dank Storage, Decorative Blocks, Ender Mail, Ender Storage, Ensorcellation, Expanded Combat, Extended Lights, Farmer's Delight, Goblin Traders, Ma Enchants, Mahou Tsukai, Masontry Blocks, More Red, Offhand Combat, Patchouli, Pretty Beaches, Psi, Psionic Peripherals, Sapience, Supplementaries, Tetra, and Traverse

**Comment by elucent** [comment]
debug.log is best, if possible you should put it in a [GitHub Gist](https://gist.github.com/).

**Comment by BioOnPC** [comment]
No problem! Link here: https://gist.github.com/BioOnPC/c1557b7f0774b169ae748558622f1734

**Comment by elucent** [comment]
So, funny thing is, I still have no idea what's causing this error. _But_, it seems like it's fixed when using eidolon-0.2.1. Maybe one of the other fixes took care of this too?

I just uploaded eidolon-0.2.1 to CurseForge, and with a little luck it should be approved soon. Whenever you get the chance, could you verify whether or not the new version fixes this issue?

**Comment by BioOnPC** [comment]
Yeah, totally! I'll report on it when I restart the server, thank you for your help!

**Comment by BioOnPC** [comment]
That seemed to do it! Thank you for answering so quickly.

**Comment by boneskull** [comment]
I’m experiencing this with the latest Eidolon in ATM6. How do I get MC to write `debug.log`?

**Comment by boneskull** [comment]
wait, this is not quite right. maybe I'm doing it wrong
