### ISSUE TITLE
Zombies do not always drop held Soul Shards

### ISSUE THREAD

**Issue by Moleculor** [elucent/eidolon#31]
**Describe the bug**
Zombies are supposed to always drop an item they have picked up off of the ground. See their wiki entry, or these [patch notes](https://minecraft.gamepedia.com/Java_Edition_12w34b). 

A zombie that picks up a Soul Shard and is then killed with a Reaper's Scythe will frequently **not** drop the Soul Shard it is holding. 

**To Reproduce**

1. Install Eidolon, Minecraft, Forge, whatever. 
2. Start a Creative world in Hard difficulty.
3. Create yourself a little testing environment, such as this: ![image](https://user-images.githubusercontent.com/3865976/103461191-21e66800-4ce2-11eb-9228-56c8fa1fdf14.png)
5. Grab yourself a Reaper's Scythe. Feel free to enchant it, but I avoided enchanting it with Looting just to make sure it wasn't interfering. 
6. `/time add 1512000t` as a Zombie's propensity to pick up items is dependent both on general difficulty setting as well as LocalDifficulty, and I believe the chance of a zombie picking up an item maxes out after 63 days of in-game time. 
7. Spawn yourself a zombie. Give him a Soul Shard. Kill him with the Reaper's Scythe. Repeat. 

For me, only four out of the ten zombies I spawned dropped Soul Shards they were holding. Or perhaps they *never* dropped the Soul Shards they were holding, and there's just a 40% chance of getting Soul Shards when killing them with a Reaper's Scythe?

Ten out of ten dropped Soul Shards when killed with a Netherite Sword. Both tests avoided the Looting enchant.

**Environment**
```
-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 7868334016 bytes (7503 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |DONE      |NOSIGNATURE
		eidolon-0.2.4.jar                                 |Eidolon                       |eidolon                       |0.2.4               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.63.jar                           |Just Enough Items             |jei                           |7.6.1.63            |DONE      |NOSIGNATURE
```

**Comment by elucent** [comment]
This will be fixed in 0.2.5. Specifically, mobs killed with rituals or the reaper's scythe will not drop items from their loot tables, but items from their inventories or equipment will now be preserved.
