### ISSUE TITLE
Game crash on empty glass bottle interact with apothecary stand.

### ISSUE THREAD

**Issue by NoRestWhenWicked** [elucent/eidolon#33]
**Describe the bug**
What went wrong?
Selecting glass bottles while the apothecary window is open (on top of boiling crucible,) crashes the game.

**To Reproduce**
What were you doing when the bug happened?
Fire underneath crucible lit on netherrack, apothecary stand on top of lit crucible, potion window open, went to move glass bottles- on interact the game crashes. Have repeated now several times, definitely continues to occur. 

**Environment**
What version of the mod were you using? Are you on singleplayer or multiplayer?
Singleplayer, newest release (0.2.6)

**Crash Report**
If the problem crashed the game, please attach a log using a [GitHub Gist](https://gist.github.com/).
https://gist.github.com/NoRestWhenWicked/cc06ebf40763813c75750b7b98dd5b98

**Comment by NoRestWhenWicked** [comment]
P.S.- Mod makers get nowhere near enough appreciation, you are amazing and I appreciate you, as will the millions of players who will enjoy your mod for years to come. Thank you for all that you do.

**Comment by NoRestWhenWicked** [comment]
Oh, it also happened with water filled glass bottles. A single bottle double clicked does NOT crash the game, but if you try to double click more than one to fill the slots it crashes. https://gist.github.com/NoRestWhenWicked/a684c0e5e92c26b32aa6ca877515fd8e

**Comment by elucent** [comment]
Should be fixed in 0.2.7, which was just uploaded to CurseForge.

**Comment by NoRestWhenWicked** [comment]
I appreciate it a lot. Not sure if this is the right place to post an idea, but the next time you want to add some rituals, would you maybe consider adding a weather set with maybe different items for the focus? As a rough idea, like snowball, water bucket, maybe the unholy symbol for lightning? Maybe like an animal sacrifice goblet for sunny weather?  (Maybe this works with serene seasons specifically? *cheesy smile, shivers*)
