### ISSUE TITLE
Unable to smelt lead ingot from dusts added by other mods.

### ISSUE THREAD

**Issue by laserlemons** [elucent/eidolon#4]
**Describe the bug**
There is no recipe for an Eidolon lead ingot to be smelted from lead dust. Some mods, like Create, add ore crushing recipes for metals that don't exist in those mods. I believe the solution is to add a smelting recipe to Eidolon that uses generic lead dust as an input.

**To Reproduce**
Install a mod that adds ore crushing recipes for other mods' metal, like Create.

**Environment**
Version 0.2.1 singleplayer

**Comment by elucent** [comment]
I think this should be provided in the next commit. Let me know if it's still absent.

**Comment by laserlemons** [comment]
"Compatibility for Eidolon's lead" was listed as a fix in the latest patch for Create. Maybe it wasn't this mod's fault after all?
