### ISSUE TITLE
Quark Oddities Matrix enchantment integration

### ISSUE THREAD

**Issue by tavanuka** [elucent/eidolon#41]
I have no idea if you ever looked into it or if it fits with the style of your amazing mod; but could you give it an overlook and see if it seems fit with your idea of the Soul enchanter on what it does!

Thats all ❤️

**Comment by elucent** [comment]
It's a neat idea, I'm vaguely familiar with it, but the soul enchanter is intentionally a different system from normal enchanting. I don't see any particular reason other than maybe a more consistent interface for an alternate soul enchanter. I may try to make the soul enchanter a bit more unique in its interface though, to emphasize how it's a distinct system.
