### ISSUE TITLE
Crash on game start in Dev Environment

### ISSUE THREAD

**Issue by NightmareTwilight** [elucent/eidolon#46]
**Describe the bug**
Crash on game start.

**To Reproduce**
On startup, in dev environment, with eidolon-0.2.7 in mods folder under run.

**Environment**
Using version 0.2.7 on singleplayer, development environment.

**Crash Report**
https://gist.github.com/NightmareTwilight/0b35ed81671704f7f3251db2140d0e9a

**Comment by NightmareTwilight** [comment]
From what I can understand, the #43 will might fix the issue.

**Comment by elucent** [comment]
This is confirmed to not be an issue on Eidolon's side, but an issue of dev environment setup. Try adding `properties 'mixin.env.disableRefMap': 'true'` to your build.gradle.
