### ISSUE TITLE
Crucible recipes not working

### ISSUE THREAD

**Issue by WretchedEgg2552** [elucent/eidolon#47]
**Describe the bug**
Recipes like the Essence of Death do not work.
I am following the instructions exactly. 1 Zombie Heart, 1 Zombie Flesh, wait for colour change, 2 bone meal and stir twice immediately and then wait for colour change, finally a Charcoal, not coal. And then it fizzles out.

**Environment**
Modpack Valhesia 3 for 1.16.4 both Multiplayer and Singleplayer. Mod Version 0.2.7

**Comment by WretchedEgg2552** [comment]
After i looked in the Code i saw that the Recipe in the book is kinda misleading, 1 Zombie Heart, 1 Zombie Flesh, immediatly stir twice and then add 2 bone meal, wait for color change (its a green) then add the charcoal. so the problem is that adding the item and stirring are changed.

**Comment by MarioSMB** [comment]
This issue should be re-opened, I encountered the same problem and this is the only place a solution has been presented.

**Comment by WretchedEgg2552** [comment]
I also wrote that reply on a Post on the Feed the Beast Subreddit. There had someone the same Problem but i closed this one because it works, And you can see this thread so i just hope the Author fixxes this with the next Version.

**Comment by MarioSMB** [comment]
It would likely be preferred to keep this open so that the developer can keep track of the issue easily and close it when it has been solved.

**Comment by WretchedEgg2552** [comment]
Okay its Reopened and Titel updated updated to clarify the problem

**Comment by elucent** [comment]
Not sure what the error is. The crucible recipe for Essence of Death in the book (reading from the code) is:

1. Add a zombie heart and rotten flesh.
2. Add two bonemeal, and stir twice.
3. Add a charcoal.

Each step corresponds to a single color change. I've cross-checked both the book chapter (CodexChapters.java) and recipe (CrucibleRegistry.java) and they are defined identically. Maybe you're just misunderstanding the mechanic?

**Comment by MarioSMB** [comment]
As I've become a bit more familiar with the process, I can see where the confusion is coming from;

Essentially, if you're not quick enough with the stirring before the item is consumed, it fails, as the item alone is counted as a stage.  
It may be worth noting in the book that this process is time sensitive.

**Comment by WretchedEgg2552** [comment]
Ah after your Comment I tested all a bit more and now its working every time. It was my bad i saw it not as a hole step and took to long to stir. So yeah i didnt understand the mechanics correctly sorry for that and thanks for your help.

I hope you keep up the nice work.
