### ISSUE TITLE
Waterlogging of Blocks

### ISSUE THREAD

**Issue by WenXin20** [elucent/eidolon#5]
**Describe the bug**
- Manually waterlogging the Plinth with a bucket does not work
- To fix, block class is missing the `implements IWaterLoggable` after the class name.
- It would also be cool to see waterlogging added to all the other blocks. It could provide for some good decorating opportunities.

**To Reproduce**
1. Place plinth
2. Right-click with a water bucket.

**Environment**
- Multiplayer
- `Eidolon v0.2.1`
- `Forge v35.1.13`
- `Minecraft v1.16.4`

**Comment by elucent** [comment]
0.2.3 adds waterlogging for plinths, stone hands, effigies, necrotic foci, and altars.
