### ISSUE TITLE
Soul enchanter can enchant invalid options

### ISSUE THREAD

**Issue by smooze** [elucent/eidolon#53]
The soul enchanter is able to apply enchants onto items that so not qualify for them; ie. feather falling on pants. 
Playing on all the mods version 1.6.4 which contains eidolon version 0.2.7
![javaw_2021-01-30_17-57-21](https://user-images.githubusercontent.com/4827696/106370094-009a8b00-6325-11eb-853e-d54909a1a8fe.png)
![javaw_2021-01-30_17-59-13](https://user-images.githubusercontent.com/4827696/106370095-01332180-6325-11eb-87b0-a35ff5442ae1.png)

**Comment by elucent** [comment]
It isn't documented anymore, but I believe the Apotheosis mod changes feather falling to be applicable to any armor piece. I can't replicate this behavior with Eidolon alone, so I believe this is just intended modpack behavior.
