### ISSUE TITLE
[Suggestion] Ars Ecclesia in off-hand allows chants during combat

### ISSUE THREAD

**Issue by MarioSMB** [elucent/eidolon#61]
This may be a bit out of scope, but it seems like a great way to incorporate more magic into the combat;

Placing the Ars Ecclesia book in the off-hand slot and right-clicking could open a small on-screen display listing the unlocked signs. Some sign combinations could be made useful while fighting mobs (such as a stun spell etc), allowing a much more diverse fighting experience for magic users.
This would also allow quick access to chanting infront of an effigy.

**Comment by elucent** [comment]
I don't plan on making chants any faster or more convenient. They're meant to be a slow, meticulous means of casting something. Accordingly, any uses they have in combat will be designed around not needing to chant very frequently.
