### ISSUE TITLE
i cant see any effects

### ISSUE THREAD

**Issue by LopsidedCsky** [elucent/eidolon#76]
i cant see anything like water in crucible or the mysterious symbols when u summon somthing but they r working anyways
i was playin singleplayer

**Comment by Feramors** [comment]
Seconded. 

I’m able to see the effect when I say...use the brazier to turn two red stone into a soul shard(the symbol in the air), but I’m either unable to see the water in the crucible boil, or it simply never boils.

**Comment by elucent** [comment]
Turn off fabulous graphics mode, or disable "better layering" in the Eidolon config.
