### ISSUE TITLE
Graphical artifacts while using ongoing rituals with shader pack

### ISSUE THREAD

**Issue by rewenx** [elucent/eidolon#78]
**Describe the bug**
When there is an ongoing ritual (e.g. Ritual of Repelling), a graphical artifact appears at the location of the reticle while using shades (see reference image)

**To Reproduce**
Use a shader pack (I used BSL), activate ongoing ritual, look at the sky (easier to see at night)

**Environment**
Eidolon 0.2.7. single-player and LAN

**Crash Report**
n/a

Ritual of repelling (orange), and ritual of deceit (green) produce these visual glitches.
![image](https://user-images.githubusercontent.com/28968821/111358267-258a5980-8658-11eb-90ce-72d8b9e1751c.png)

**Unrelated Commentary**
Your mod is extremely well-designed, programmed, and the textures are spot-on. Thank you!

**Comment by elucent** [comment]
It's pretty hard to address issues with shaders on my end reliably. One thing you can try is turning off "better layering" in the Eidolon client config - this does some different rendering than vanilla to avoid depth issues, but has the unfortunate side effect of breaking in weird rendering environments. Past that, though, I unfortunately don't plan on investigating visual issues with shaders.
