### ISSUE TITLE
Ritual of Daylight resets game day to 0. 

### ISSUE THREAD

**Issue by Moleculor** [elucent/eidolon#9]
**Describe the bug**
I was testing some stuff in creative and noticed an oddity about the way Ritual of Daylight behaves. The New Moon became a Full Moon the moment the ritual activated. 

Turns out that Minecraft keeps track of what the in-game date is (I think listed via LocalDifficulty, listed on F3, left side, one of the bottom few lines). The ritual of daylight (which accelerates night to day) resets this count to 0.

This will likely have knock-on effects in various ways. My understanding is that illager patrols will not appear for the first five in-game days. This likely functions as a reset for that counter.

In addition, some mods utilize the in game date for basic mod functionality. Serene Seasons, for example, determines which of the twelve seasonal phases it's in (plus what day of those seasons) on this same in-game date. Reset the in-game date, reset all of the seasons back to Early Spring. Every time. Even if you're in Late Summer when you run the ritual. 

**To Reproduce**

1. Install Forge, Eidolon, JEI, Curios, and any other mod you care to install.
2. Push F3. Observe Local Difficulty, and the `(Day 0)` listed there.
3. Use `/time add 47.5d` to jump forward by fourty-seven and a half days. 
4. Observe the moon's phase and take note of it. 
5. Observe Local Difficulty's listed Day is now higher.
6. Perform the Ritual of Daylight.
7. Observe the moon change phase the instant the ritual completes. 
8. Observe Local Difficulty's listed Day reset to 0. 

**Environment**
Singleplayer. Creative.
```
-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 5915822336 bytes (5641 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |DONE      |NOSIGNATURE
		eidolon-0.2.jar                                   |Eidolon                       |eidolon                       |0.2                 |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
```

EDIT: I just realized that GDLauncher wasn't showing me that v0.2.2 was out. I updated to that and it still occurs.

**Comment by elucent** [comment]
Should be fixed in the next commit.
