### ISSUE TITLE
[Enhancement] JSON Recipe System & Ore Dictionary Tags

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [elucent/eidolon#92]
It would be nice if you made Magic Workbench and Crucible recipes support ore dict tags. (Such as the mind shielding plate with Thermal's Lead Ingots or Crimson Essence with Mekanism's Sulfur Dust)

**Comment by BeansBeefBroccoli** [comment]
This would also require moving to a Json recipe format.

**Comment by denzuko** [comment]
Would love to see this too, its a blocker for a modpack I'm toying on. been trying to get either kubejs or https://www.curseforge.com/minecraft/mc-mods/eidolon-data-recipes to work.
